// <auto-generated />
using System;
using dawn.ftp.ui.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dawn.ftp.ui.ui.Migrations
{
    [DbContext(typeof(SqlLiteDbContext))]
    partial class SqlLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("dawn.ftp.ui.Models.SftpConnectionProperty", b =>
                {
                    b.Property<ulong>("ConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostOsIcon")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseKeyAuth")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConnectionId");

                    b.ToTable("SftpConnectionProperties");
                });

            modelBuilder.Entity("dawn.ftp.ui.Models.TransferModels.FileTransferModel", b =>
                {
                    b.Property<long>("FileTransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progress")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteIP")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLocation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TransferEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransferStart")
                        .HasColumnType("TEXT");

                    b.HasKey("FileTransferId");

                    b.ToTable("FileTransferModels");
                });
#pragma warning restore 612, 618
        }
    }
}
